site_name: !ENV [SITE_NAME, "DevOps Jeremy"]
site_url: https://DevOpsJeremy.github.io
theme:
  name: material
  features:
    - navigation.indexes
plugins:
  - search
  - blog:
      blog_toc: true
      pagination_per_page: 10
  - tags:
      tags_file: blog/tags.md
  - include_dir_to_nav
  - markdownextradata: {}
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
nav:
  - Home: index.md
  - Blog:
      - Posts: blog/index.md
      - Tags: blog/tags.md
  - Documentation: documentation
  - About: about.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/square-x-twitter
      name: X
      link: https://x.com/DevOpsJeremy
    - icon: fontawesome/brands/github
      name: Github
      link: https://github.com/DevOpsJeremy
    - icon: fontawesome/brands/instagram
      name: Instagram
      link: https://www.instagram.com/yousuckatpowershell
extra_css:
  - assets/stylesheets/custom.css
hooks:
  - hooks/socialmedia.py
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg