site_name: !ENV [SITE_NAME, "DevOps Jeremy"]
site_url: https://DevOpsJeremy.github.io
site_repo: https://github.com/DevOpsJeremy/DevOpsJeremy.github.io
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - exclude-search:
      exclude:
        - documentation/generate/*
  - blog:
      blog_toc: true
      pagination_per_page: 10
  - tags:
      tags_file: blog/tags.md
  - include_dir_to_nav
  - markdownextradata: {}
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
nav:
  - Home: index.md
  - Blog:
      - Posts: blog/index.md
      - Tags: blog/tags.md
  - Documentation: documentation
  - About: about.md
extra:
  comments: true
  generator: false
  social:
    - icon: fontawesome/brands/square-x-twitter
      name: X
      link: https://x.com/DevOpsJeremy
    - icon: fontawesome/brands/github
      name: Github
      link: https://github.com/DevOpsJeremy
    - icon: fontawesome/brands/instagram
      name: Instagram
      link: https://www.instagram.com/yousuckatpowershell
extra_css:
  - assets/stylesheets/custom.css
hooks:
  - hooks/socialmedia.py
markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details
