name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  documentation:
    strategy:
      matrix:
        container: mcr.microsoft.com/powershell
        item:
          - container: mcr.microsoft.com/powershell
            name: Generate PowerShell documentation
            run: pwsh -File .github/scripts/generate_docs/generate_pwsh.ps1
    runs-on: ubuntu-latest
    container: "{{ matrix.container }}"
    steps:
      - name: "{{ matrix.item.name }}"
        run: "{{ matrix.item.run }}"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
