name: ci
on:
  push:
    branches: ['*']
      # - main
permissions:
  contents: write
jobs:
  # documentation:
  #   strategy:
  #     matrix:
  #       item:
  #         - container: mcr.microsoft.com/powershell
  #           name: Generate PowerShell documentation
  #           run: pwsh -File .github/scripts/generate_docs/generate_pwsh.ps1 -Modules $(pwd)/$GENERATE_PATH/powershell/*
  #   runs-on: ubuntu-latest
  #   container: ${{ matrix.item.container }}
  #   env:
  #     GENERATE_PATH: docs/documentation/generate
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: ${{ matrix.item.name }}
  #       run: ${{ matrix.item.run }}
  deploy:
    runs-on: ubuntu-latest
    # needs: documentation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install .
      - run: mkdocs gh-deploy --force
      - run: |
          set -x
          pwd
          ls
          ls docs/other/Photography/ || echo "No Photography yet"
          ls docs/other/Photography/images-resized/ || echo "No resized images yet"
          ls site/ || echo "No site yet"
          ls site/other/Photography/ || echo "No Photography yet"
          ls site/other/Photography/images-resized/ || echo "No resized images yet"
